<?xml version="1.0" ?>
<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />
    <!--xacro:include filename="$(find robot_description)/urdf/lidar.urdf.xacro" /-->
    <!--xacro:include filename="$(find robot_description)/urdf/depth.urdf.xacro" /-->

    <xacro:property name="chassis_length" value="0.435"/>
    <xacro:property name="chassis_width" value="0.265"/>
    <xacro:property name="chassis_height" value="0.138"/>
    <xacro:property name="wheel_radius" value="0.07"/>
    <xacro:property name="wheel_thickness" value="0.08"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.05"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>
    <xacro:property name="mass" value="1.0"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="yellow">
        <color rgba="1 1 0 1"/>
    </material>

    <link name="base_link">
    </link>

    <link name="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 -0.138" rpy="0 0 0"/>
    </joint>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name='chassis'>
    
    <inertial>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        <mass value="${mass}" />
        <inertia ixx="${(1/12) * mass * (chassis_width*chassis_width+chassis_height*chassis_height)}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * (chassis_length*chassis_length+chassis_height*chassis_height)}" iyz="0.0"
                 izz="${(1/12) * mass * (chassis_length*chassis_length+chassis_width*chassis_width)}" />
    </inertial>
    <visual>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
        <geometry>
            <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
    </collision>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0.09 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                     izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0.09 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                     izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x - 0.02} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${caster_wheel_mass}" />
            <inertia ixx="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" ixy="0.0" ixz="0.0"
                     iyy="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" iyz="0.0"
                     izz="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
       
	<!-- I AM SPEED start -->
	  <!-- T start -->
	  <!-- Rectangle on the top of base_link -->
	  <link name="head_of_T">
	    <visual>
	      <geometry>
		<box size="0.1 0.5 0.02"/> <!-- Размеры прямоугольника (высота, ширина, длина) -->
	      </geometry>
	      <material name="green">  
		<color rgba="0.0 1.0 0 1.0"/>
	      </material>
	    </visual>

	    <collision>
	      <geometry>
		<box size="0.1 0.5 0.02"/> <!-- Размеры прямоугольника для коллизий -->
	      </geometry>
	    </collision>

	    <!-- Определение инерции прямоугольника -->
	    <inertial>
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <mass value="0.1"/> <!-- Масса прямоугольника -->
	      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/> <!-- Моменты инерции -->
	    </inertial>
	  </link>

	  <!-- Joint to connect top_rectangle_link to base_link -->
	  <joint name="head_of_T_joint" type="fixed">
	    <parent link="base_link"/>
	    <child link="head_of_T"/>
	    <origin xyz="-0.05 0.0 ${chassis_height/2 + 0.07}" rpy="0 0 0"/> <!-- Высота прямоугольника относительно base_link -->
	  </joint>

	    <!-- Rectangle at a 90 degree -->
	  <link name="angled_rectangle_link_1">
	    <visual>
	      <geometry>
		<box size="0.25 0.1 0.02"/> <!-- Размеры прямоугольника (высота, ширина, длина) -->
	      </geometry>
	      <material name="green">  
		<color rgba="0 1.0 0 1.0"/>
	      </material>
	    </visual>

	    <collision>
	      <geometry>
		<box size="0.25 0.1 0.02"/> <!-- Размеры прямоугольника для коллизий -->
	      </geometry>
	    </collision>

	    <!-- Определение инерции прямоугольника -->
	    <inertial>
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <mass value="0.1"/> <!-- Масса прямоугольника -->
	      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/> <!-- Моменты инерции -->
	    </inertial>
	  </link>

	  <!-- Joint to connect angled_rectangle_link_1 to base_link at a 45-degree angle -->
	  <joint name="angled_rectangle_joint_1" type="fixed">
	    <parent link="base_link"/>
	    <child link="angled_rectangle_link_1"/>
	    <origin xyz="0.1 0 ${chassis_height/2 + 0.07}" rpy="0 0 0"/> 
	    <axis xyz="1 0 0"/> <!-- Ось вращения вдоль z-оси (вертикальная ось) -->
	  </joint>

	  
	  <!-- T end -->

	  <!-- I AM SPEED end-->
    
</robot>

